# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Company.create(title: 'Genmab A/S', ticker: 'CHXEUR:GENC', GTicker: "GEN", exch: "CPH", description: "Genmab A/S is a Danish biotechnology company, founded in February 1999 by Florian Schönharting, at the time managing director of BankInvest Biomedical venture fund. Genmab is based in Copenhagen. Internationally, it operates through the subsidiaries Genmab BV in Utrecht, The Netherlands, and Genmab, Inc in Princeton, New Jersey, USA. The Company is publicly traded on the NASDAQ OMX Copenhagen A/S. The company has two approved antibodies, Arzerra® (ofatumumab) for the treatment of certain chronic lymphocytic leukemia indications and DARZALEX™ (daratumumab) for the treatment of heavily pretreated or double refractory multiple myeloma. Daratumumab is in clinical development for additional multiple myeloma indications and for non-Hodgkin’s lymphoma. They also have a broad clinical and pre-clinical product pipeline.",
              focus: "Cancer", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/33/Genmab.svg/1280px-Genmab.svg.png")

Company.create(title: 'Saniona AB', ticker: 'LSIN_DLY:0RQJ', GTicker: "SANION", exch: "STO", description: "Saniona is a research and development company focused on drugs for diseases of the central nervous system, autoimmune diseases, metabolic diseases and treatment of pain. The company has a significant portfolio of potential drug candidates at preclinical and clinical stage. The research is focused on ion channels, which makes up a unique protein class that enables and controls the passage of charged ions across cell membranes. Saniona has ongoing collaboration agreements with Boehringer Ingelheim GmbH, Proximagen Ltd., Productos Medix, S.A and Luc Therapeutics, Inc. Saniona is based in Copenhagen, Denmark, where it has a research center of high international standard. Saniona is listed at Nasdaq Stockholm Small Cap and has about 5,000 shareholders. The company's share is traded under the ticker SANION. ",
              focus: "central nervous system, autoimmune diseases, metabolic diseases, pain", logo: "https://shop.umbraco.com/media/2989381/morten-nielsen-saniona_log.png?width=500&height=154.24430641821948")